name: agora_chat_uikit
description: A set of ui components adapted to the chat sdk can quickly build a chat page
  and chat through the chat sdk by invoking the ui components.
version: 2.0.0
homepage: https://www.agora.io/

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  # im_flutter_sdk: ^4.6.1
  agora_chat_sdk:
    path: ../../../agora_chat_sdk_130/

  flutter_sound_record: ^3.3.2

  shared_preferences: ^2.2.2

  chat_uikit_theme: ^0.0.7
  # chat_uikit_theme:
  #   path: ../chat_uikit_theme/

  path_provider: ^2.1.1

  file_picker: ^6.1.1

  audioplayers: ^5.2.1

  image_picker: ^1.0.5

  video_thumbnail: ^0.5.3

  video_player: ^2.8.6

  flutter_localization: ^0.2.0

  scroll_to_index: ^3.0.1

  cached_network_image: ^3.3.1

  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.ease.em_chat_uikit
        pluginClass: FlutterChatUikitPlugin
      ios:
        pluginClass: FlutterChatUikitPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/emojis/
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages

